# This is a basic workflow to help you get started with Actions
name: CI
on:
   push:
     branches:
       - main
     tags:
       - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Verify tag
        run: |
            VERSION=$(grep VERSION_NAME gradle.properties | awk -F= '{ print $2 }' | sed "s/-SNAPSHOT//")
            if [ "${{ steps.vars.outputs.tag }}" != "v$VERSION" ]; then {
              echo "Tag ${{ steps.vars.outputs.tag }} does not match the package version ($VERSION)"
              exit 1
            } fi
      - name: create release
        run: |
            curl \
               -X POST \
               -H "Authorization: token $GITHUB_TOKEN" \
                  https://api.github.com/repos/wenxi-zeng/segment-hackthon/releases \
               -d '{"tag_name": "${{ env.RELEASE_VERSION }}", "name": "${{ env.RELEASE_VERSION }}", "body": "Release of version ${{ env.RELEASE_VERSION }}", "draft": false, "prerelease": false, "generate_release_notes": true}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
