# This is a basic workflow to help you get started with Actions

name: CI

on:
   push:
     branches:
       - main
     tags:
       - '*'
       
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

      - name: create release
        run: |
            curl \
               -X POST \
               -H "Authorization: token $GITHUB_TOKEN" \
                  https://api.github.com/repos/wenxi-zeng/segment-hackthon/releases \
               -d '{"tag_name": "${{ GITHUB_ENV }}", "target_commitish": "main", "name": "${{ GITHUB_ENV }}", "body": "Release of version ${{ GITHUB_ENV }}", "draft": false, "prerelease": false, "generate_release_notes": true}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

