# This is a basic workflow to help you get started with Actions

name: CI

on:
   push:
     branches:
       - main
     tags:
       - '*'
       
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: create release
        run: |
            curl \
               -X POST \
               -H "Authorization: token $GITHUB_TOKEN" \
                  https://api.github.com/repos/wenxi-zeng/segment-hackthon/releases \
               -d '{"tag_name": "v0.0.3", "target_commitish": "main", "name": "v0.0.3", "body": "Release of version v0.0.3", "draft": false, "prerelease": false, "generate_release_notes": true}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
