# This is a basic workflow to help you get started with Actions

name: CI

on:
   push:
     branches:
       - main
     tags:
       - '*'
       
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: create release
        run: |
            curl \
               -X POST \
               -H "Authorization: token $GITHUB_TOKEN" \
                  https://api.github.com/repos/wenxi-zeng/segment-hackthon/releases \
               -d '{"tag_name": "$RELEASE_VERSION", "target_commitish": "main", "name": "$RELEASE_VERSION", "body": "Release of version $RELEASE_VERSION", "draft": false, "prerelease": false, "generate_release_notes": true}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}

