# This is a basic workflow to help you get started with Actions
name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        run: |
            curl \
               -X POST \
               -H "Authorization: token $GITHUB_TOKEN" \
                  https://api.github.com/repos/${{github.repository}}/releases \
               -d '{"tag_name": "v0.0.8", "name": "v0.0.8", "body": "Release of version v0.0.8", "draft": false, "prerelease": false, "generate_release_notes": true}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
